apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 2368
    protocol: TCP
  selector:
    app: ghost-blog