apiVersion: v1
kind: Service
metadata:
  name: helloworld-app-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: helloworld-app